package com.tuannh.model;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Addresses generated by hbm2java
 */
@Entity
@Table(name = "tuan_addresses")
public class Addresses implements java.io.Serializable {

	private Integer addressId;
	private String line1;
	private String line2;
	private String townCity;
	private Integer zipPostCode;
	private String stateProviceContry;
	private String country;
	private String otherDetails;
	private Set<Banks> bankses = new HashSet<Banks>(0);

	public Addresses() {
	}

	public Addresses(String line1, String line2, String townCity, Integer zipPostCode, String stateProviceContry,
			String country, String otherDetails, Set<Banks> bankses) {
		this.line1 = line1;
		this.line2 = line2;
		this.townCity = townCity;
		this.zipPostCode = zipPostCode;
		this.stateProviceContry = stateProviceContry;
		this.country = country;
		this.otherDetails = otherDetails;
		this.bankses = bankses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Address_ID", unique = true, nullable = false)
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@Column(name = "Line_1")
	public String getLine1() {
		return this.line1;
	}

	public void setLine1(String line1) {
		this.line1 = line1;
	}

	@Column(name = "Line_2")
	public String getLine2() {
		return this.line2;
	}

	public void setLine2(String line2) {
		this.line2 = line2;
	}

	@Column(name = "Town_City")
	public String getTownCity() {
		return this.townCity;
	}

	public void setTownCity(String townCity) {
		this.townCity = townCity;
	}

	@Column(name = "Zip_PostCode")
	public Integer getZipPostCode() {
		return this.zipPostCode;
	}

	public void setZipPostCode(Integer zipPostCode) {
		this.zipPostCode = zipPostCode;
	}

	@Column(name = "State_Provice_Contry")
	public String getStateProviceContry() {
		return this.stateProviceContry;
	}

	public void setStateProviceContry(String stateProviceContry) {
		this.stateProviceContry = stateProviceContry;
	}

	@Column(name = "Country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "Other_Details")
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addresses")
	public Set<Banks> getBankses() {
		return this.bankses;
	}

	public void setBankses(Set<Banks> bankses) {
		this.bankses = bankses;
	}

}
