package com.tuannh.model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * CartCenters generated by hbm2java
 */
@Entity
@Table(name = "Cart_Centers")
public class CartCenters implements java.io.Serializable {

	private Integer cardCenterId;
	private String cartCenterDetails;
	private Integer amount;
	private Set<TransactionData> transactiomData = new HashSet<TransactionData>(0);

	public CartCenters(Integer cardCenterId) {
		super();
		this.cardCenterId = cardCenterId;
	}

	public CartCenters() {
	}

	public CartCenters(String cartCenterDetails,Integer amount) {
		this.cartCenterDetails = cartCenterDetails;
		this.amount=amount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Card_Center_ID", unique = true, nullable = false)
	public Integer getCardCenterId() {
		return this.cardCenterId;
	}

	public void setCardCenterId(Integer cardCenterId) {
		this.cardCenterId = cardCenterId;
	}

	@Column(name = "Cart_Center_Details", length = 65535)
	public String getCartCenterDetails() {
		return this.cartCenterDetails;
	}

	public void setCartCenterDetails(String cartCenterDetails) {
		this.cartCenterDetails = cartCenterDetails;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cardEnter")
	public Set<TransactionData> getTransactiomData() {
		return transactiomData;
	}

	public void setTransactiomData(Set<TransactionData> transactiomData) {
		this.transactiomData = transactiomData;
	}

	@Column(name = "Amount")
	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}
	
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return cardCenterId+cartCenterDetails+amount;
	}

	
}
