package com.tuannh.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DataTransfers generated by hbm2java
 */
@Entity
@Table(name = "tuan_data_transfers")
public class DataTransfers implements java.io.Serializable {

	private Integer dataTranferId;
	private Acquisitions acquisitions;
	private Merchants merchants;
	private String dataTransferDate;
	private String merchantsFees;
	private String otherDetail;
	private Set<TransactionData> transactionData = new HashSet<TransactionData>(0);

	public DataTransfers() {
	}
	
	

	public DataTransfers(Integer dataTranferId) {
		super();
		this.dataTranferId = dataTranferId;
	}



	public DataTransfers(Acquisitions acquisitions, Merchants merchants, String dataTransferDate, String merchantsFees,
			String otherDetail) {
		this.acquisitions = acquisitions;
		this.merchants = merchants;
		this.dataTransferDate = dataTransferDate;
		this.merchantsFees = merchantsFees;
		this.otherDetail = otherDetail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Data_Tranfer_ID", unique = true, nullable = false)
	public Integer getDataTranferId() {
		return this.dataTranferId;
	}

	public void setDataTranferId(Integer dataTranferId) {
		this.dataTranferId = dataTranferId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Acquisition_ID")
	public Acquisitions getAcquisitions() {
		return this.acquisitions;
	}

	public void setAcquisitions(Acquisitions acquisitions) {
		this.acquisitions = acquisitions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Merchants_ID")
	public Merchants getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Merchants merchants) {
		this.merchants = merchants;
	}

	@Column(name = "Data_Transfer_Date")
	public String getDataTransferDate() {
		return this.dataTransferDate;
	}

	public void setDataTransferDate(String dataTransferDate) {
		this.dataTransferDate = dataTransferDate;
	}

	@Column(name = "Merchants_Fees")
	public String getMerchantsFees() {
		return this.merchantsFees;
	}

	public void setMerchantsFees(String merchantsFees) {
		this.merchantsFees = merchantsFees;
	}

	@Column(name = "Other_Detail")
	public String getOtherDetail() {
		return this.otherDetail;
	}

	public void setOtherDetail(String otherDetail) {
		this.otherDetail = otherDetail;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dataTransfer")
	public Set<TransactionData> getTransactionData() {
		return transactionData;
	}

	public void setTransactionData(Set<TransactionData> transactiomData) {
		this.transactionData = transactiomData;
	}

}
