package com.tuannh.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Merchants generated by hbm2java
 */
@Entity
@Table(name = "Merchants")
public class Merchants implements java.io.Serializable {

	private Integer merchantId;
	private String merchantName;
	private String otherDetails;
	private Integer amount;
	private Set<DataTransfers> dataTransferses = new HashSet<DataTransfers>(0);

	public Merchants() {
	}

	public Merchants(String merchantName, String otherDetails, Set<DataTransfers> dataTransferses) {
		this.merchantName = merchantName;
		this.otherDetails = otherDetails;
		this.dataTransferses = dataTransferses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Merchant_ID", unique = true, nullable = false)
	public Integer getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(Integer merchantId) {
		this.merchantId = merchantId;
	}

	@Column(name = "Merchant_Name", length = 65535)
	public String getMerchantName() {
		return this.merchantName;
	}

	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName;
	}

	@Column(name = "Other_Details", length = 65535)
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchants")
	public Set<DataTransfers> getDataTransferses() {
		return this.dataTransferses;
	}

	public void setDataTransferses(Set<DataTransfers> dataTransferses) {
		this.dataTransferses = dataTransferses;
	}

	@Column(name = "Amount")
	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}
}
