package com.tuannh.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefTransactionTypes generated by hbm2java
 */
@Entity
@Table(name = "tuan_ref_transaction_types")
public class RefTransactionTypes implements java.io.Serializable {

	private Integer transactionTypeCode;
	private String transactionTypeDescription;
	private Set<TransactionData> transactiomData = new HashSet<TransactionData>(0);

	public RefTransactionTypes() {
	}
	
	public RefTransactionTypes(Integer transactionTypeCode) {
		super();
		this.transactionTypeCode = transactionTypeCode;
	}



	public RefTransactionTypes(String transactionTypeDescription) {
		this.transactionTypeDescription = transactionTypeDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Transaction_Type_Code", unique = true, nullable = false)
	public Integer getTransactionTypeCode() {
		return this.transactionTypeCode;
	}

	public void setTransactionTypeCode(Integer transactionTypeCode) {
		this.transactionTypeCode = transactionTypeCode;
	}

	@Column(name = "Transaction_Type_Description")
	public String getTransactionTypeDescription() {
		return this.transactionTypeDescription;
	}

	public void setTransactionTypeDescription(String transactionTypeDescription) {
		this.transactionTypeDescription = transactionTypeDescription;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transaction")
	public Set<TransactionData> getTransactiomData() {
		return transactiomData;
	}

	public void setTransactiomData(Set<TransactionData> transactiomData) {
		this.transactiomData = transactiomData;
	}

}
