
package com.tuannh.model;




import java.util.HashSet;
import java.util.Set;

import org.springframework.data.annotation.Id;
import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;



/**
 * Acquisitions generated by hbm2java
 */
@Table(value = "tuan_acquisitions")
public class Acquisitions implements java.io.Serializable {

	private Integer acquisitionId;
	private Banks banks;
	private String acquisitionDate;
	private String otherDetails;
	private Set<DataTransfers> dataTransferses = new HashSet<DataTransfers>(0);

	public Acquisitions() {
	}

	public Acquisitions(Banks banks, String acquisitionDate, String otherDetails, Set<DataTransfers> dataTransferses) {
		this.banks = banks;
		this.acquisitionDate = acquisitionDate;
		this.otherDetails = otherDetails;
		this.dataTransferses = dataTransferses;
	}

	@PrimaryKey
	@Column(value = "Acquisition_ID")
	public Integer getAcquisitionId() {
		return this.acquisitionId;
	}

	public void setAcquisitionId(Integer acquisitionId) {
		this.acquisitionId = acquisitionId;
	}

	@Column(value = "Bank_ID")
	public Banks getBanks() {
		return this.banks;
	}

	public void setBanks(Banks banks) {
		this.banks = banks;
	}

	@Column(value = "Acquisition_Date")
	public String getAcquisitionDate() {
		return this.acquisitionDate;
	}

	public void setAcquisitionDate(String acquisitionDate) {
		this.acquisitionDate = acquisitionDate;
	}

	@Column(value = "Other_Details")
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

	
	public Set<DataTransfers> getDataTransferses() {
		return this.dataTransferses;
	}

	public void setDataTransferses(Set<DataTransfers> dataTransferses) {
		this.dataTransferses = dataTransferses;
	}

}
