
package com.tuannh.model;




import java.sql.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;



/**
 * Acquisitions generated by hbm2java
 */
@Table(value = "tuan_acquisitions")
public class Acquisitions implements java.io.Serializable {
	
	@PrimaryKey
	private UUID acquisitionId;
	private UUID banks;
	private Date acquisitionDate;
	private String otherDetails;
//	private Set<DataTransfers> dataTransferses = new HashSet<DataTransfers>(0);

	public Acquisitions() {
	}

	public Acquisitions(UUID banks, Date acquisitionDate, String otherDetails) {
		this.banks = banks;
		this.acquisitionDate = acquisitionDate;
		this.otherDetails = otherDetails;
//		this.dataTransferses = dataTransferses;
	}

	
	@Column(value = "Acquisition_ID")
	public UUID getAcquisitionId() {
		return this.acquisitionId;
	}

	public void setAcquisitionId(UUID acquisitionId) {
		this.acquisitionId = acquisitionId;
	}

	@Column(value = "Bank_ID")
	public UUID getBanks() {
		return this.banks;
	}

	public void setBanks(UUID banks) {
		this.banks = banks;
	}

	@Column(value = "Acquisition_Date")
	public Date getAcquisitionDate() {
		return this.acquisitionDate;
	}

	public void setAcquisitionDate(Date acquisitionDate) {
		this.acquisitionDate = acquisitionDate;
	}

	@Column(value = "Other_Details")
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

	
//	public Set<DataTransfers> getDataTransferses() {
//		return this.dataTransferses;
//	}
//
//	public void setDataTransferses(Set<DataTransfers> dataTransferses) {
//		this.dataTransferses = dataTransferses;
//	}

}
