package com.tuannh.model;


import java.util.Set;
import java.util.UUID;

import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;


/**
 * Addresses generated by hbm2java
 */
@Table(value = "tuan_addresses")
public class Addresses implements java.io.Serializable {
	
	@PrimaryKey
	private UUID addressId;
	private String line1;
	private String line2;
	private String townCity;
	private Integer zipPostCode;
	private String stateProviceContry;
	private String country;
	private String otherDetails;
//	private Set<Banks> bankses = new HashSet<Banks>(0);

	public Addresses() {
	}

	public Addresses(String line1, String line2, String townCity, Integer zipPostCode, String stateProviceContry,
			String country, String otherDetails) {
		this.line1 = line1;
		this.line2 = line2;
		this.townCity = townCity;
		this.zipPostCode = zipPostCode;
		this.stateProviceContry = stateProviceContry;
		this.country = country;
		this.otherDetails = otherDetails;
//		this.bankses = bankses;
	}

	
	@Column(value = "Address_ID")
	public UUID getAddressId() {
		return this.addressId;
	}

	public void setAddressId(UUID addressId) {
		this.addressId = addressId;
	}

	@Column(value = "Line_1")
	public String getLine1() {
		return this.line1;
	}

	public void setLine1(String line1) {
		this.line1 = line1;
	}

	@Column(value = "Line_2")
	public String getLine2() {
		return this.line2;
	}

	public void setLine2(String line2) {
		this.line2 = line2;
	}

	@Column(value = "Town_City")
	public String getTownCity() {
		return this.townCity;
	}

	public void setTownCity(String townCity) {
		this.townCity = townCity;
	}

	@Column(value = "Zip_PostCode")
	public Integer getZipPostCode() {
		return this.zipPostCode;
	}

	public void setZipPostCode(Integer zipPostCode) {
		this.zipPostCode = zipPostCode;
	}

	@Column(value = "State_Provice_Contry")
	public String getStateProviceContry() {
		return this.stateProviceContry;
	}

	public void setStateProviceContry(String stateProviceContry) {
		this.stateProviceContry = stateProviceContry;
	}

	@Column(value = "Country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(value = "Other_Details")
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

	
//	public Set<Banks> getBankses() {
//		return this.bankses;
//	}
//
//	public void setBankses(Set<Banks> bankses) {
//		this.bankses = bankses;
//	}

}
