package com.tuannh.model;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;


/**
 * Banks generated by hbm2java
 */

@Table(value = "tuan_banks")
public class Banks implements java.io.Serializable {

	@PrimaryKey
	private UUID bankId;
	private UUID addresses;
	private String bankName;
	private String bankDetails;
//	private Set<Acquisitions> acquisitionses = new HashSet<Acquisitions>(0);

	public Banks() {
	}

	public Banks(UUID addresses, String bankName, String bankDetails) {
		this.addresses = addresses;
		this.bankName = bankName;
		this.bankDetails = bankDetails;
//		this.acquisitionses = acquisitionses;
	}

	
	@Column(value = "Bank_ID")
	public UUID getBankId() {
		return this.bankId;
	}

	public void setBankId(UUID bankId) {
		this.bankId = bankId;
	}

	@Column(value = "Address_ID")
	public UUID getAddresses() {
		return this.addresses;
	}

	public void setAddresses(UUID addresses) {
		this.addresses = addresses;
	}

	@Column(value = "Bank_Name")
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(value = "Bank_Details")
	public String getBankDetails() {
		return this.bankDetails;
	}

	public void setBankDetails(String bankDetails) {
		this.bankDetails = bankDetails;
	}

//	public Set<Acquisitions> getAcquisitionses() {
//		return this.acquisitionses;
//	}
//
//	public void setAcquisitionses(Set<Acquisitions> acquisitionses) {
//		this.acquisitionses = acquisitionses;
//	}

}
