package com.tuannh.model;



import java.util.HashSet;
import java.util.Set;

import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * CartCenters generated by hbm2java
 */
@Table(value = "tuan_cart_centers")
public class CartCenters  {
	
	@PrimaryKey
	private Integer card_Center_Id;
	private String cartCenterDetails;
	private Integer amount;
	
//	private Set<TransactionData> transactiomData = new HashSet<TransactionData>(0);

//	public CartCenters(Integer cardCenterId) {
//		super();
//		this.card_Center_Id = cardCenterId;
//	}

	public CartCenters() {
	}

//	public CartCenters(String cartCenterDetails,Integer amount) {
//		this.cartCenterDetails = cartCenterDetails;
//		this.amount=amount;
//	}
	
	
	
	public CartCenters(Integer cardCenterId, String cartCenterDetails, Integer amount) {
		super();
		this.card_Center_Id = cardCenterId;
		this.cartCenterDetails = cartCenterDetails;
		this.amount = amount;
	}

	
	@Column(value = "card_Center_Id")
	public Integer getCardCenterId() {
		return this.card_Center_Id;
	}

	public void setCardCenterId(Integer cardCenterId) {
		this.card_Center_Id = cardCenterId;
	}

	@Column(value = "Cart_Center_Details")
	public String getCartCenterDetails() {
		return this.cartCenterDetails;
	}

	public void setCartCenterDetails(String cartCenterDetails) {
		this.cartCenterDetails = cartCenterDetails;
	}

//	public Set<TransactionData> getTransactiomData() {
//		return transactiomData;
//	}
//
//	public void setTransactiomData(Set<TransactionData> transactiomData) {
//		this.transactiomData = transactiomData;
//	}

	@Column( value = "Amount")
	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}
	
//	@Override
//	public String toString() {
//		// TODO Auto-generated method stub
//		return cardCenterId+cartCenterDetails+amount;
//	}

	
}
