package com.tuannh.model;

import java.util.UUID;

import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

import com.datastax.driver.core.LocalDate;

/**
 * DataTransfers generated by hbm2java
 */
@Table(value = "tuan_data_transfers")
public class DataTransfers implements java.io.Serializable {

	@PrimaryKey
	private UUID data_tranfer_id;
	private UUID acquisitions;
	private UUID merchants;
	private LocalDate dataTransferDate;
	private String merchantsFees;
	private String otherDetail;
//	private Set<TransactionData> transactionData = new HashSet<TransactionData>(0);

	public DataTransfers() {
	}
	
	

	public DataTransfers(UUID dataTranferId) {
		super();
		this.data_tranfer_id = dataTranferId;
	}



	public DataTransfers(UUID acquisitions, UUID merchants,LocalDate dataTransferDate, String merchantsFees,
			String otherDetail) {
		this.acquisitions = acquisitions;
		this.merchants = merchants;
		this.dataTransferDate = dataTransferDate;
		this.merchantsFees = merchantsFees;
		this.otherDetail = otherDetail;
	}

	
	public UUID getDataTranferId() {
		return this.data_tranfer_id;
	}

	public void setDataTranferId(UUID dataTranferId) {
		this.data_tranfer_id = dataTranferId;
	}

	@Column(value = "Acquisition_ID")
	public UUID getAcquisitions() {
		return this.acquisitions;
	}

	public void setAcquisitions(UUID acquisitions) {
		this.acquisitions = acquisitions;
	}

	@Column(value = "Merchants_ID")
	public UUID getMerchants() {
		return this.merchants;
	}

	public void setMerchants(UUID merchants) {
		this.merchants = merchants;
	}

	@Column(value = "Data_Transfer_Date")
	public LocalDate getDataTransferDate() {
		return this.dataTransferDate;
	}

	public void setDataTransferDate(LocalDate dataTransferDate) {
		this.dataTransferDate = dataTransferDate;
	}

	@Column(value = "Merchants_Fees")
	public String getMerchantsFees() {
		return this.merchantsFees;
	}

	public void setMerchantsFees(String merchantsFees) {
		this.merchantsFees = merchantsFees;
	}

	@Column(value = "Other_Detail")
	public String getOtherDetail() {
		return this.otherDetail;
	}

	public void setOtherDetail(String otherDetail) {
		this.otherDetail = otherDetail;
	}
	
//	public Set<TransactionData> getTransactionData() {
//		return transactionData;
//	}
//
//	public void setTransactionData(Set<TransactionData> transactiomData) {
//		this.transactionData = transactiomData;
//	}

}
