package com.tuannh.model;

import java.util.HashSet;
import java.util.Set;

import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * Merchants generated by hbm2java
 */
@Table(value = "tuan_merchants")
public class Merchants implements java.io.Serializable {

	@PrimaryKey
	private Integer merchant_id;
	private String merchantName;
	private String otherDetails;
	private Integer amount;
	// private Set<DataTransfers> dataTransferses = new HashSet<DataTransfers>(0);

	public Merchants() {
	}

	// public Merchants(String merchantName, String otherDetails, Set<DataTransfers>
	// dataTransferses) {
	// this.merchantName = merchantName;
	// this.otherDetails = otherDetails;
	// this.dataTransferses = dataTransferses;
	// }

	// @PrimaryKey
	// @Column(value = "Merchant_ID")
	public Integer getMerchantId() {
		return this.merchant_id;
	}

	public Merchants(Integer merchant_id, String merchantName, String otherDetails, Integer amount) {
		super();
		this.merchant_id = merchant_id;
		this.merchantName = merchantName;
		this.otherDetails = otherDetails;
		this.amount = amount;
	}

	public void setMerchantId(Integer merchantId) {
		this.merchant_id = merchantId;
	}

	@Column(value = "Merchant_Name")
	public String getMerchantName() {
		return this.merchantName;
	}

	public void setMerchantName(String merchantName) {
		this.merchantName = merchantName;
	}

	@Column(value = "Other_Details")
	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

//	public Set<DataTransfers> getDataTransferses() {
//		return this.dataTransferses;
//	}
//
//	public void setDataTransferses(Set<DataTransfers> dataTransferses) {
//		this.dataTransferses = dataTransferses;
//	}

	@Column(value = "Amount")
	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}
}
