package com.tuannh.model;

import java.util.HashSet;
import java.util.Set;

import org.springframework.data.cassandra.mapping.Column;
import org.springframework.data.cassandra.mapping.PrimaryKey;
import org.springframework.data.cassandra.mapping.Table;

/**
 * RefTransactionTypes generated by hbm2java
 */
@Table(value = "tuan_ref_transaction_types")
public class RefTransactionTypes implements java.io.Serializable {

	private Integer transactionTypeCode;
	private String transactionTypeDescription;
	private Set<TransactionData> transactiomData = new HashSet<TransactionData>(0);

	public RefTransactionTypes() {
	}
	
	public RefTransactionTypes(Integer transactionTypeCode) {
		super();
		this.transactionTypeCode = transactionTypeCode;
	}



	public RefTransactionTypes(String transactionTypeDescription) {
		this.transactionTypeDescription = transactionTypeDescription;
	}

	@PrimaryKey
	@Column(value = "Transaction_Type_Code")
	public Integer getTransactionTypeCode() {
		return this.transactionTypeCode;
	}

	public void setTransactionTypeCode(Integer transactionTypeCode) {
		this.transactionTypeCode = transactionTypeCode;
	}

	@Column(value = "Transaction_Type_Description")
	public String getTransactionTypeDescription() {
		return this.transactionTypeDescription;
	}

	public void setTransactionTypeDescription(String transactionTypeDescription) {
		this.transactionTypeDescription = transactionTypeDescription;
	}
	
	public Set<TransactionData> getTransactiomData() {
		return transactiomData;
	}

	public void setTransactiomData(Set<TransactionData> transactiomData) {
		this.transactiomData = transactiomData;
	}

}
